### ISSUE TITLE
Failed to read the 'localStorage' property from 'Window': Access is denied for this document

### ISSUE THREAD

**Issue by wildpow** [apollographql/apollo-client-devtools#106]
Apollo dev tools do not load here is the error when I inspect the Apollo dev tool window

`
devtools.js:1 DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
    at new e (chrome-extension://jdkknkkbebbapilgoeccciglkfbmbnfm/dist/devtools.js:1:907084)
    at new n (chrome-extension://jdkknkkbebbapilgoeccciglkfbmbnfm/dist/devtools.js:1:678128)
    at constructClassInstance (chrome-extension://jdkknkkbebbapilgoeccciglkfbmbnfm/dist/devtools.js:1:585617)
    at beginWork (chrome-extension://jdkknkkbebbapilgoeccciglkfbmbnfm/dist/devtools.js:1:588247)
    at r (chrome-extension://jdkknkkbebbapilgoeccciglkfbmbnfm/dist/devtools.js:1:592259)
    at o (chrome-extension://jdkknkkbebbapilgoeccciglkfbmbnfm/dist/devtools.js:1:592580)
    at a (chrome-extension://jdkknkkbebbapilgoeccciglkfbmbnfm/dist/devtools.js:1:592816)
    at k (chrome-extension://jdkknkkbebbapilgoeccciglkfbmbnfm/dist/devtools.js:1:596339)
    at T (chrome-extension://jdkknkkbebbapilgoeccciglkfbmbnfm/dist/devtools.js:1:596076)
    at m (chrome-extension://jdkknkkbebbapilgoeccciglkfbmbnfm/dist/devtools.js:1:595208)
u @ devtools.js:1
`

**Comment by wildpow** [comment]
```
Main._createAppUI: 26.3017578125ms
inspector.js:8443 Main._showAppUI: 73.092041015625ms
inspector.js:8443 Main._initializeTarget: 10.427001953125ms
devtools_compatibility.js:309 [Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
_decodeBase64 @ devtools_compatibility.js:309
devtools.js:1 DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
    at new e (chrome-extension://jdkknkkbebbapilgoeccciglkfbmbnfm/dist/devtools.js:1:907084)
    at new n (chrome-extension://jdkknkkbebbapilgoeccciglkfbmbnfm/dist/devtools.js:1:678128)
    at constructClassInstance (chrome-extension://jdkknkkbebbapilgoeccciglkfbmbnfm/dist/devtools.js:1:585617)
    at beginWork (chrome-extension://jdkknkkbebbapilgoeccciglkfbmbnfm/dist/devtools.js:1:588247)
    at r (chrome-extension://jdkknkkbebbapilgoeccciglkfbmbnfm/dist/devtools.js:1:592259)
    at o (chrome-extension://jdkknkkbebbapilgoeccciglkfbmbnfm/dist/devtools.js:1:592580)
    at a (chrome-extension://jdkknkkbebbapilgoeccciglkfbmbnfm/dist/devtools.js:1:592816)
    at k (chrome-extension://jdkknkkbebbapilgoeccciglkfbmbnfm/dist/devtools.js:1:596339)
    at T (chrome-extension://jdkknkkbebbapilgoeccciglkfbmbnfm/dist/devtools.js:1:596076)
    at m (chrome-extension://jdkknkkbebbapilgoeccciglkfbmbnfm/dist/devtools.js:1:595208)
u @ devtools.js:1
devtools.html:1 Error in event handler for (unknown): SecurityError: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
    at new e (chrome-extension://jdkknkkbebbapilgoeccciglkfbmbnfm/dist/devtools.js:1:907084)
    at new n (chrome-extension://jdkknkkbebbapilgoeccciglkfbmbnfm/dist/devtools.js:1:678128)
    at constructClassInstance (chrome-extension://jdkknkkbebbapilgoeccciglkfbmbnfm/dist/devtools.js:1:585617)
    at beginWork (chrome-extension://jdkknkkbebbapilgoeccciglkfbmbnfm/dist/devtools.js:1:588247)
    at r (chrome-extension://jdkknkkbebbapilgoeccciglkfbmbnfm/dist/devtools.js:1:592259)
    at o (chrome-extension://jdkknkkbebbapilgoeccciglkfbmbnfm/dist/devtools.js:1:592580)
    at a (chrome-extension://jdkknkkbebbapilgoeccciglkfbmbnfm/dist/devtools.js:1:592816)
    at k (chrome-extension://jdkknkkbebbapilgoeccciglkfbmbnfm/dist/devtools.js:1:596339)
    at T (chrome-extension://jdkknkkbebbapilgoeccciglkfbmbnfm/dist/devtools.js:1:596076)
    at m (chrome-extension://jdkknkkbebbapilgoeccciglkfbmbnfm/dist/devtools.js:1:595208)
devtools.html:1 Error in event handler for (unknown): SecurityError: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
    at new e (chrome-extension://jdkknkkbebbapilgoeccciglkfbmbnfm/dist/devtools.js:1:907084)
    at new n (chrome-extension://jdkknkkbebbapilgoeccciglkfbmbnfm/dist/devtools.js:1:678128)
    at constructClassInstance (chrome-extension://jdkknkkbebbapilgoeccciglkfbmbnfm/dist/devtools.js:1:585617)
    at beginWork (chrome-extension://jdkknkkbebbapilgoeccciglkfbmbnfm/dist/devtools.js:1:588247)
    at r (chrome-extension://jdkknkkbebbapilgoeccciglkfbmbnfm/dist/devtools.js:1:592259)
    at o (chrome-extension://jdkknkkbebbapilgoeccciglkfbmbnfm/dist/devtools.js:1:592580)
    at a (chrome-extension://jdkknkkbebbapilgoeccciglkfbmbnfm/dist/devtools.js:1:592816)
    at k (chrome-extension://jdkknkkbebbapilgoeccciglkfbmbnfm/dist/devtools.js:1:596339)
    at T (chrome-extension://jdkknkkbebbapilgoeccciglkfbmbnfm/dist/devtools.js:1:596076)
    at m (chrome-extension://jdkknkkbebbapilgoeccciglkfbmbnfm/dist/devtools.js:1:595208)
```

**Comment by ashutoshrishi** [comment]
This was happening to me too until I **unchecked** `block third-party cookies` in my Chrome settings. Must be something to do with the iframe and third-party cookie interaction.

**Comment by yordis** [comment]
Does anyone knows how to whitelist the devtool on Chrome? 

The URL of this is encoded on base64 as a JSON format so I am really lost on how I could do that.

**Comment by WizardOfOgz** [comment]
@yordis Allowed an exception `chrome-extension://jdkknkkbebbapilgoeccciglkfbmbnfm/`.

**Comment by justinanastos** [comment]
Thanks for reporting this! I'm going to close it out in favor of #118.

**Comment by haripriyakalahasti** [comment]
Adding this line above the modheader setup resolved my issue

driver.get("chrome-extension://idgpnmonknjnojddfkpgkljpfnnfcklj/icon.png");
