### ISSUE TITLE
Feature Request: Enable the devtools per iframe

### ISSUE THREAD

**Issue by evans** [apollographql/apollo-client-devtools#120]
With pages that contain iframes, such as codesandbox, we should be able to access the Apollo Client instance for an embedded iframe.

**Comment by lukejagodzinski** [comment]
Please add this feature. Now it's not possible to access Apollo Client instance when you test your application which is loaded into iframe widget.

**Comment by jhurwitz** [comment]
For reference, this was the approach the React devtools took: https://github.com/facebook/react-devtools/pull/440

**Comment by brunoreis** [comment]
These hooks works sometimes for me, but I'm researching a way to make them more stable: 

```
window.__APOLLO_DEVTOOLS_GLOBAL_HOOK__ = window.parent.__APOLLO_DEVTOOLS_GLOBAL_HOOK__
window.parent.__APOLLO_CLIENT__ = window.__APOLLO_CLIENT__
```

**Comment by lukejagodzinski** [comment]
@brunoreis yep we're using this kind of hack in our project and it works pretty well, but it would be good to have something working out of the box

**Comment by brunoreis** [comment]
I agree. It works for me, but I have to restart chrome once in a while. Don't ask me why.

**Comment by codejamninja** [comment]
When I try it, I get the following error . . .

```
Uncaught DOMException: Blocked a frame with origin "http://localhost:3000" from accessing a cross-origin frame.
    at Module../src/index.tsx (http://localhost:3000/static/js/main.chunk.js:1853:15)
    at __webpack_require__ (http://localhost:3000/static/js/bundle.js:786:30)
    at fn (http://localhost:3000/static/js/bundle.js:151:20)
    at Object.1 (http://localhost:3000/static/js/main.chunk.js:8216:18)
    at __webpack_require__ (http://localhost:3000/static/js/bundle.js:786:30)
    at checkDeferredModules (http://localhost:3000/static/js/bundle.js:46:23)
    at Array.webpackJsonpCallback [as push] (http://localhost:3000/static/js/bundle.js:33:19
```

**Comment by hwillson** [comment]
Moved to https://github.com/apollographql/apollo-client-devtools/discussions/380 - thanks!

**Comment by nicobrinkkemper** [comment]
Since I see a lot of issues, I will just post my Storybook solution here since it's kind of inspired by it, but they didn't work for my requirement which was live switching mock/backend in storybook (dynamic client)
```ts
import { ApolloClient, useApolloClient } from "@apollo/client";
import { useEffect, type PropsWithChildren } from "react";

declare global {
  interface Window {
    __APOLLO_DEVTOOLS_GLOBAL_HOOK__: { ApolloClient: ApolloClient<unknown> };
    __APOLLO_CLIENT__: ApolloClient<unknown>;
  }
}
/**
 * Makes apollo dev tools work in iframes
 * see discussion here: https://github.com/apollographql/apollo-client-devtools/issues/120
 * this is my own solution, not the one from the discussion
 * For devtools:
 *  - https://addons.mozilla.org/nl/firefox/addon/apollo-developer-tools/
 *  - https://chromewebstore.google.com/detail/apollo-client-devtools/jdkknkkbebbapilgoeccciglkfbmbnfm
 * */
export function ApolloDevToolFix({ children }: PropsWithChildren) {
  const client = useApolloClient();
  useEffect(() => {
    window.parent.__APOLLO_CLIENT__ = client; //
    if (!window.parent.__APOLLO_DEVTOOLS_GLOBAL_HOOK__) return;
    window.parent.__APOLLO_DEVTOOLS_GLOBAL_HOOK__.ApolloClient = client;
  }, [client]);
  return children;
}
```
