### ISSUE TITLE
unable to load devtool properly. Failed to execute 'postMessage' on 'Window'

### ISSUE THREAD

**Issue by zhpadvoiski** [apollographql/apollo-client-devtools#1258]
Error occurs in dev mode when during the initial page load
```
Uncaught DOMException: Failed to execute 'postMessage' on 'Window': URL object could not be cloned.
    at Object.postMessage (chrome-extension://jdkknkkbebbapilgoeccciglkfbmbnfm/hook.js:1:12273)
    at Object.send (chrome-extension://jdkknkkbebbapilgoeccciglkfbmbnfm/hook.js:1:11729)
    at r (chrome-extension://jdkknkkbebbapilgoeccciglkfbmbnfm/hook.js:1:14709)
    at chrome-extension://jdkknkkbebbapilgoeccciglkfbmbnfm/hook.js:1:15291
```

the bug is likely caused by this PR - https://github.com/apollographql/apollo-client-devtools/pull/1245
**Intended outcome:**

**Actual outcome:**

No error

**How to reproduce the issue:**
Start up any app in dev mode with Apollo Client and apollo-dev-tool enabled

**Desktop (please complete the following information):**

- Browser [e.g. chrome, safari] chrome
- Browser version [e.g. 22]  122.0.6261.112 (arm64)
- Extension version [e.g. 3.0] 4.8.1

**Comment by jerelmiller** [comment]
Hey @zhpadvoiski 👋 

You're right, that PR does look like the culprit here. Thanks for bringing this to our attention! 

I'm curious, are you storing `URL` instances directly in your cache (i.e. writing them in a `merge` function somewhere?) It seems `URL` instances don't work with [`structuredClone`](https://developer.mozilla.org/en-US/docs/Web/API/structuredClone), which `window.postMessage` uses under the hood. Seems `JSON.stringify` actually does handle serializing `URL` instances correctly, so that would explain why its suddenly breaking for you. I'll look at getting this reverted.

In the mean time, if you need a workaround, consider using a [`read` function](https://www.apollographql.com/docs/react/caching/cache-field-behavior#the-read-function) to perform the conversion from string -> `URL`. I'll try and get a fix out for this in the next couple days.

**Comment by jerelmiller** [comment]
This should be fixed with https://github.com/apollographql/apollo-client-devtools/pull/1259 which we'll plan to release with 4.8.2. We should be able to get this out fairly quickly 🙂

**Comment by Sitronik** [comment]
Looks like I have a similar problem

```js
Uncaught DOMException: Failed to execute 'postMessage' on 'Window': #<Object> could not be cloned.
    at Object.postMessage (chrome-extension://jdkknkkbebbapilgoeccciglkfbmbnfm/hook.js:1:12273)
    at Object.send (chrome-extension://jdkknkkbebbapilgoeccciglkfbmbnfm/hook.js:1:11729)
    at r (chrome-extension://jdkknkkbebbapilgoeccciglkfbmbnfm/hook.js:1:14709)
    at chrome-extension://jdkknkkbebbapilgoeccciglkfbmbnfm/hook.js:1:15415
    at i (chrome-extension://jdkknkkbebbapilgoeccciglkfbmbnfm/hook.js:1:11525)
    at r (chrome-extension://jdkknkkbebbapilgoeccciglkfbmbnfm/hook.js:1:12170)
```

**Comment by jerelmiller** [comment]
Turns out the `JSON.stringify` on the cache that was previously done was a LOT more important than I realized 😅. We should be able to get this fix out today.
