### ISSUE TITLE
GraphiQL introspection of client-side schema breaks with extend keyword

### ISSUE THREAD

**Issue by peggyrayzis** [apollographql/apollo-client-devtools#132]
Steps to reproduce:

1. Open Pupstagram: https://codesandbox.io/s/r5qp83z0yq
2. Change line 2 of `schema.js` to `extend type Image`
3. Open devtools and click on GraphiQL docs explorer

```
Error: no value resolved
    at Object.complete (chrome-extension://gcedmodoecoempkiebidmigpnkfopjph/dist/devtools.js:1:695329)
    at complete (chrome-extension://gcedmodoecoempkiebidmigpnkfopjph/dist/devtools.js:1:376930)
    at t.s (chrome-extension://gcedmodoecoempkiebidmigpnkfopjph/dist/devtools.js:1:673216)
    at t.n.emit (chrome-extension://gcedmodoecoempkiebidmigpnkfopjph/dist/devtools.js:1:308077)
    at chrome-extension://gcedmodoecoempkiebidmigpnkfopjph/dist/devtools.js:1:381756
    at EventImpl.dispatchToListener (extensions::event_bindings:403:22)
    at Event.publicClassPrototype.(anonymous function) [as dispatchToListener] (extensions::utils:138:26)
    at EventImpl.dispatch_ (extensions::event_bindings:387:35)
    at EventImpl.dispatch (extensions::event_bindings:409:17)
    at Event.publicClassPrototype.(anonymous function) [as dispatch] (extensions::utils:138:26)
```

**Comment by tomasvarg** [comment]
This happens also when using [descriptions](https://www.apollographql.com/docs/graphql-tools/generate-schema.html#descriptions) in a client-side schema or when there are errors in the schema definition (like forgetting to add a field type). (Line numbers at the stack trace are the same.)

**Comment by Arseniy-II** [comment]
I believe [descriptions](https://www.apollographql.com/docs/graphql-tools/generate-schema.html#descriptions) shouldn't cause that error

**Comment by tsaiDavid** [comment]
Any updates on this?

**Comment by Ihatetomatoes** [comment]
I had the same issue as tomasvarg. Writing descriptions for the client-side schema like this works:

```
type Wizzard {
    # Index of the currently active wizzard step.
    index: Int
}
```

**Comment by justinanastos** [comment]
Thanks @peggyrayzis . I looked checked two things:

1. I used a fork of the fullstack example (https://github.com/justinanastos/fullstack-tutorial/tree/justin/apollo-pre-2.5) and reproduced exactly what you saw.
2. I also checked [`master` of `fullstack-tutorial`](https://github.com/apollographql/fullstack-tutorial) and it appears as though things are now working as expected. The tutorial is using alpha releases for both [`apollo-client`](https://github.com/apollographql/fullstack-tutorial/blob/0f54410e26ecba4f79a9c0bb880aa31357474241/final/client/package.json#L8) and [`react-apollo`](https://github.com/apollographql/fullstack-tutorial/blob/0f54410e26ecba4f79a9c0bb880aa31357474241/final/client/package.json#L15). 

I'm going to leave this ticket open until those land.

**Comment by basicdays** [comment]
Just ran into this issue defining typeDefs with `apollo-link-state` and including an `extend Query` declaration in that. Will keep that commented out until 2.5 lands and I'll see if that fixes anything.

**Comment by justinanastos** [comment]
Resolved in [v2.1.7](https://github.com/apollographql/apollo-client-devtools/releases/tag/v2.1.7)
