### ISSUE TITLE
Queries tab is empty

### ISSUE THREAD

**Issue by SergeyKhval** [apollographql/apollo-client-devtools#1480]
Error on Queries tab:

```
ApolloError: Failed to execute 'postMessage' on 'Window': #<Object> could not be cloned.

ApolloError
    at new t (chrome-extension://jdkknkkbebbapilgoeccciglkfbmbnfm/panel.js:1:336837)
    at chrome-extension://jdkknkkbebbapilgoeccciglkfbmbnfm/panel.js:1:374825
    at i (chrome-extension://jdkknkkbebbapilgoeccciglkfbmbnfm/panel.js:1:344588)
    at chrome-extension://jdkknkkbebbapilgoeccciglkfbmbnfm/panel.js:1:344502
    at new Promise (<anonymous>)
    at Object.then (chrome-extension://jdkknkkbebbapilgoeccciglkfbmbnfm/panel.js:1:344468)
    at Object.next (chrome-extension://jdkknkkbebbapilgoeccciglkfbmbnfm/panel.js:1:344598)
    at st (chrome-extension://jdkknkkbebbapilgoeccciglkfbmbnfm/panel.js:1:256763)
    at lt (chrome-extension://jdkknkkbebbapilgoeccciglkfbmbnfm/panel.js:1:257276)
    at t.next (chrome-extension://jdkknkkbebbapilgoeccciglkfbmbnfm/panel.js:1:257816)
```

### `@apollo/client` version
3.11.4

### Apollo Client Devtools version
4.18.1

**Comment by phryneas** [comment]
This should be solved in https://github.com/apollographql/apollo-client-devtools/releases/tag/v4.18.2 - please give it a try :)
