### ISSUE TITLE
RPC_MESSAGE_TIMEOUT when using Apollo Client

### ISSUE THREAD

**Issue by leonardfountain** [apollographql/apollo-client-devtools#1485]
Error on Cache tab:

```
ApolloError: RPC_MESSAGE_TIMEOUT

ApolloError
    at new t (chrome-extension://jdkknkkbebbapilgoeccciglkfbmbnfm/panel.js:1:336837)
    at chrome-extension://jdkknkkbebbapilgoeccciglkfbmbnfm/panel.js:1:374825
    at i (chrome-extension://jdkknkkbebbapilgoeccciglkfbmbnfm/panel.js:1:344588)
    at chrome-extension://jdkknkkbebbapilgoeccciglkfbmbnfm/panel.js:1:344502
    at new Promise (<anonymous>)
    at Object.then (chrome-extension://jdkknkkbebbapilgoeccciglkfbmbnfm/panel.js:1:344468)
    at Object.next (chrome-extension://jdkknkkbebbapilgoeccciglkfbmbnfm/panel.js:1:344598)
    at st (chrome-extension://jdkknkkbebbapilgoeccciglkfbmbnfm/panel.js:1:256763)
    at lt (chrome-extension://jdkknkkbebbapilgoeccciglkfbmbnfm/panel.js:1:257276)
    at t.next (chrome-extension://jdkknkkbebbapilgoeccciglkfbmbnfm/panel.js:1:257816)
```

### Apollo Client Devtools version
4.18.2

**Comment by phryneas** [comment]
This error usually occurs when your browser updates the DevTools while they are already opened and connected to your page.

Could you please try to restart your browser and see if that makes it work again?
