### ISSUE TITLE
Error on Queries tab

### ISSUE THREAD

**Issue by Totonno** [apollographql/apollo-client-devtools#1500]
Error on Queries tab:

```
ApolloError: Cannot read properties of undefined (reading 'map')

ApolloError
    at new t (chrome-extension://jdkknkkbebbapilgoeccciglkfbmbnfm/panel.js:1:339389)
    at chrome-extension://jdkknkkbebbapilgoeccciglkfbmbnfm/panel.js:1:377644
    at i (chrome-extension://jdkknkkbebbapilgoeccciglkfbmbnfm/panel.js:1:347140)
    at chrome-extension://jdkknkkbebbapilgoeccciglkfbmbnfm/panel.js:1:347054
    at new Promise (<anonymous>)
    at Object.then (chrome-extension://jdkknkkbebbapilgoeccciglkfbmbnfm/panel.js:1:347020)
    at Object.next (chrome-extension://jdkknkkbebbapilgoeccciglkfbmbnfm/panel.js:1:347150)
    at st (chrome-extension://jdkknkkbebbapilgoeccciglkfbmbnfm/panel.js:1:259259)
    at lt (chrome-extension://jdkknkkbebbapilgoeccciglkfbmbnfm/panel.js:1:259772)
    at t.next (chrome-extension://jdkknkkbebbapilgoeccciglkfbmbnfm/panel.js:1:260312)
```

### Apollo Client Devtools version
4.18.4

**Comment by jerelmiller** [comment]
Hey @Totonno 👋  

Thanks for opening the issue! Is there any more information you can give on what happened to cause this error? Any more details you can give would be greatly appreciated!
