### ISSUE TITLE
Not working with apollo-link-state

### ISSUE THREAD

**Issue by MichelDiz** [apollographql/apollo-client-devtools#152]
ac-devtools works but don't load anything. I'm running a simple example provided on docs.

```
{
  "errors": [
    {
      "message": "forward is not a function",
      "locations": [
        "TypeError: forward is not a function\n    at RestLink.request (http://localhost:1234/src.f69400ca.js:37868:24)\n    at http://localhost:1234/src.f69400ca.js:28062:25\n    at StateLink.request (http://localhost:1234/src.f69400ca.js:58996:29)\n    at ApolloLink.request (http://localhost:1234/src.f69400ca.js:28061:24)\n    at http://localhost:1234/src.f69400ca.js:28062:25\n    at ApolloLink.request (http://localhost:1234/src.f69400ca.js:30824:14)\n    at ApolloLink.request (http://localhost:1234/src.f69400ca.js:28061:24)\n    at chrome-extension://jdkknkkbebbapilgoeccciglkfbmbnfm/dist/backend.js:1:3681\n    at e.request (chrome-extension://jdkknkkbebbapilgoeccciglkfbmbnfm/dist/backend.js:1:38654)\n    at chrome-extension://jdkknkkbebbapilgoeccciglkfbmbnfm/dist/backend.js:1:3681"
      ]
    }
  ]
}
```

**Comment by hwillson** [comment]
Can you share the exact code your running that leads to seeing this error?

**Comment by justinanastos** [comment]
Hi @MichelDiz ! I'm going to close this issue pending a reproduction. Thanks for filing the report
