### ISSUE TITLE
ApolloError: Cannot read properties of null (reading 'definitions')

### ISSUE THREAD

**Issue by cod3master** [apollographql/apollo-client-devtools#1605]
Error on Queries tab:

```
ApolloError: Cannot read properties of null (reading 'definitions')

ApolloError
    at new t (chrome-extension://jdkknkkbebbapilgoeccciglkfbmbnfm/panel.js:1:354936)
    at chrome-extension://jdkknkkbebbapilgoeccciglkfbmbnfm/panel.js:1:393140
    at i (chrome-extension://jdkknkkbebbapilgoeccciglkfbmbnfm/panel.js:1:362636)
    at chrome-extension://jdkknkkbebbapilgoeccciglkfbmbnfm/panel.js:1:362550
    at new Promise (<anonymous>)
    at Object.then (chrome-extension://jdkknkkbebbapilgoeccciglkfbmbnfm/panel.js:1:362516)
    at Object.next (chrome-extension://jdkknkkbebbapilgoeccciglkfbmbnfm/panel.js:1:362646)
    at ht (chrome-extension://jdkknkkbebbapilgoeccciglkfbmbnfm/panel.js:1:274793)
    at mt (chrome-extension://jdkknkkbebbapilgoeccciglkfbmbnfm/panel.js:1:275306)
    at t.next (chrome-extension://jdkknkkbebbapilgoeccciglkfbmbnfm/panel.js:1:275846)
```

### Apollo Client Devtools version
4.18.15 (Chrome)

**Comment by jerelmiller** [comment]
Thanks for the report @cod3master! We'll see if we can look into this soon 🙂

**Comment by jerelmiller** [comment]
@cod3master is there a particular query or something you're doing that is causing this issue? I see that we're trying to read definitions from a query when handling queries from the the explorer. Is that what is triggering this error for you?
