### ISSUE TITLE
Empty explorer and docs

### ISSUE THREAD

**Issue by sean-bennett112** [apollographql/apollo-client-devtools#394]
I'm trying to get the devtools working as a quick way to give internal users a way to explore the schema and create queries for their use cases. Unfortunately when trying this out, it looks like the explorer and doc panels are both persistently empty.

![explorer](https://user-images.githubusercontent.com/2096022/106811593-79bc1a00-6666-11eb-9308-d40d11a998ec.png)

When looking at any errors the extension was raising, I found the below:

```
Error in event handler: GraphQLError: Syntax Error: Expected Name, found }
    at t.syntaxError (chrome-extension://jdkknkkbebbapilgoeccciglkfbmbnfm/dist/devtools.js:1:404972)
    at X (chrome-extension://jdkknkkbebbapilgoeccciglkfbmbnfm/dist/devtools.js:1:242031)
    at f (chrome-extension://jdkknkkbebbapilgoeccciglkfbmbnfm/dist/devtools.js:1:231442)
    at Q (chrome-extension://jdkknkkbebbapilgoeccciglkfbmbnfm/dist/devtools.js:1:240904)
    at ne (chrome-extension://jdkknkkbebbapilgoeccciglkfbmbnfm/dist/devtools.js:1:242512)
    at z (chrome-extension://jdkknkkbebbapilgoeccciglkfbmbnfm/dist/devtools.js:1:241512)
    at chrome-extension://jdkknkkbebbapilgoeccciglkfbmbnfm/dist/devtools.js:1:239446
    at P (chrome-extension://jdkknkkbebbapilgoeccciglkfbmbnfm/dist/devtools.js:1:239554)
    at p (chrome-extension://jdkknkkbebbapilgoeccciglkfbmbnfm/dist/devtools.js:1:233626)
    at ne (chrome-extension://jdkknkkbebbapilgoeccciglkfbmbnfm/dist/devtools.js:1:242534)
devtools.html:1 Error in event handler: GraphQLError: Syntax Error: Expected Name, found }
    at t.syntaxError (chrome-extension://jdkknkkbebbapilgoeccciglkfbmbnfm/dist/devtools.js:1:404972)
    at X (chrome-extension://jdkknkkbebbapilgoeccciglkfbmbnfm/dist/devtools.js:1:242031)
    at f (chrome-extension://jdkknkkbebbapilgoeccciglkfbmbnfm/dist/devtools.js:1:231442)
    at Q (chrome-extension://jdkknkkbebbapilgoeccciglkfbmbnfm/dist/devtools.js:1:240904)
    at ne (chrome-extension://jdkknkkbebbapilgoeccciglkfbmbnfm/dist/devtools.js:1:242512)
    at z (chrome-extension://jdkknkkbebbapilgoeccciglkfbmbnfm/dist/devtools.js:1:241512)
    at chrome-extension://jdkknkkbebbapilgoeccciglkfbmbnfm/dist/devtools.js:1:239446
    at P (chrome-extension://jdkknkkbebbapilgoeccciglkfbmbnfm/dist/devtools.js:1:239554)
    at p (chrome-extension://jdkknkkbebbapilgoeccciglkfbmbnfm/dist/devtools.js:1:233626)
    at ne (chrome-extension://jdkknkkbebbapilgoeccciglkfbmbnfm/dist/devtools.js:1:242534)
```

Based on those errors, my (wild) guess is that the schema is empty or something when the extension tries to populate those two panels.

However, everything else works. I can see queries and mutations that have been made, I can view the cache, I can even run arbitrary queries from the GraphiQL panel. I just can't see the explorer or docs.

This is for an authenticated graphql endpoint as well, in case that's important. I can probably share the `ApolloClient` `link` code if that would help at all.

Tested on the below systems:

**Desktop**
 - OS: Windows 10
 - Browser: chrome
 - Browser version: 86
 - Extension version: 2.3.5

**Desktop**
 - OS: Linux
 - Browser: chrome
 - Browser version: 86
 - Extension version: 2.3.5

**Desktop**
 - OS: Linux
 - Browser: firefox
 - Browser version: 82
 - Extension version: 2.3.5

**Comment by sean-bennett112** [comment]
Oh, and we're currently on `"@apollo/client": "^3.2.1",`

**Comment by sean-bennett112** [comment]
Closing this, as it turns out after debugging that Hasura was generating malformed introspection results based on empty yaml.
