### ISSUE TITLE
Dev Tools crashes after deleting only query field

### ISSUE THREAD

**Issue by ctjlewis** [apollographql/apollo-client-devtools#507]
**Intended outcome:**

No crashing.

**Actual outcome:**

Apollo Client Dev Tools crashes after deleting the only field in a query while editing in the Build panel. 

**How to reproduce the issue:**

This seems to be a result of the recent update. I do not have the time to make a repro, but here is a video of the crash (after deleting `__typename`) and a copy of the error. If it is not immediately obvious what is causing this, I can set aside time and create a repro in the coming days.

https://user-images.githubusercontent.com/1657236/113494167-78af3980-94ab-11eb-83c5-e41a25596176.mp4

```none
panel.js:formatted:62719 GraphQLError: Syntax Error: Expected Name, found "}".
    at i (chrome-extension://jdkknkkbebbapilgoeccciglkfbmbnfm/panel.js:1:882204)
    at e.t.expectToken (chrome-extension://jdkknkkbebbapilgoeccciglkfbmbnfm/panel.js:1:935753)
    at e.t.parseName (chrome-extension://jdkknkkbebbapilgoeccciglkfbmbnfm/panel.js:1:919891)
    at e.t.parseField (chrome-extension://jdkknkkbebbapilgoeccciglkfbmbnfm/panel.js:1:922343)
    at e.t.parseSelection (chrome-extension://jdkknkkbebbapilgoeccciglkfbmbnfm/panel.js:1:922270)
    at e.t.many (chrome-extension://jdkknkkbebbapilgoeccciglkfbmbnfm/panel.js:1:936733)
    at e.t.parseSelectionSet (chrome-extension://jdkknkkbebbapilgoeccciglkfbmbnfm/panel.js:1:922119)
    at e.t.parseOperationDefinition (chrome-extension://jdkknkkbebbapilgoeccciglkfbmbnfm/panel.js:1:921185)
    at e.t.parseDefinition (chrome-extension://jdkknkkbebbapilgoeccciglkfbmbnfm/panel.js:1:920262)
    at e.t.many (chrome-extension://jdkknkkbebbapilgoeccciglkfbmbnfm/panel.js:1:936733)
```

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] `Ubuntu`
 - Browser [e.g. chrome, safari] `Chrome`
 - Browser version [e.g. 22] `Version 89.0.4389.114 (Official Build) (64-bit)`
 - Extension version [e.g. 3.0] `3.0.3`

**Comment by ctjlewis** [comment]
Further demonstrating the issue / how I will work around it:

https://user-images.githubusercontent.com/1657236/113494234-202c6c00-94ac-11eb-8c67-ffaa95a3265d.mp4

**Comment by ctjlewis** [comment]
One more example:

https://user-images.githubusercontent.com/1657236/113494468-08ee7e00-94ae-11eb-9ddb-d53308749c8a.mp4

**Comment by ctjlewis** [comment]
In fact, even just typing "q" immediately causes a crash:

https://user-images.githubusercontent.com/1657236/113494507-80241200-94ae-11eb-85e0-d258d94d026c.mp4

**Comment by ctjlewis** [comment]
Good work @hwillson!

**Comment by hwillson** [comment]
Thanks @ctjlewis - sorry about that! 3.0.4 has been submitted to the Chrome store, so hopefully it will be live shortly. We really need to expand our test suite / test approach for this plugin 😳.

**Comment by ctjlewis** [comment]
No worries at all! I will edit my comment in Chrome web store in the AM, I just wanted to bring it to everyone's attention ASAP.

I also tried to look over the codebase myself but wasn't able to identify the source of the error. Thanks for handling it so quickly!
