### ISSUE TITLE
May potentially crash a React 18.0.0 app rendered with renderToPipeableStream (server) / hydrateRoot (client)

### ISSUE THREAD

**Issue by hrgui** [apollographql/apollo-client-devtools#839]
**Intended outcome:**
Expected the app to render as is w/o issues when extension is enabled.

Should see Hello World

**Actual outcome:**

Hello World renders, then

App crashes. See stack trace.

```
react-dom.development.js:14344 Uncaught Error: Hydration failed because the initial UI does not match what was rendered on the server.
    at throwOnHydrationMismatch (react-dom.development.js:14344:1)
    at tryToClaimNextHydratableInstance (react-dom.development.js:14372:1)
    at updateHostComponent$1 (react-dom.development.js:20636:1)
    at beginWork (react-dom.development.js:22373:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:4157:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4206:1)
    at invokeGuardedCallback (react-dom.development.js:4270:1)
    at beginWork$1 (react-dom.development.js:27243:1)
    at performUnitOfWork (react-dom.development.js:26392:1)
    at workLoopSync (react-dom.development.js:26303:1)
    
react-dom.development.js:22670 Uncaught DOMException: Failed to execute 'appendChild' on 'Node': Only one element on document allowed.
    at appendChildToContainer (http://localhost:4000/main.js:11331:16)
    at insertOrAppendPlacementNodeIntoContainer (http://localhost:4000/main.js:24122:7)
    at insertOrAppendPlacementNodeIntoContainer (http://localhost:4000/main.js:24128:7)
    at insertOrAppendPlacementNodeIntoContainer (http://localhost:4000/main.js:24128:7)
    at commitPlacement (http://localhost:4000/main.js:24102:9)
    at commitMutationEffectsOnFiber (http://localhost:4000/main.js:24621:9)
    at commitMutationEffects_complete (http://localhost:4000/main.js:24514:7)
    at commitMutationEffects_begin (http://localhost:4000/main.js:24503:7)
    at commitMutationEffects (http://localhost:4000/main.js:24473:3)
    at commitRootImpl (http://localhost:4000/main.js:26924:5)
    
react-dom.development.js:20583 Uncaught Error: There was an error while hydrating. Because the error happened outside of a Suspense boundary, the entire root will switch to client rendering.
    at updateHostRoot (react-dom.development.js:20583:1)
    at beginWork (react-dom.development.js:22370:1)
    at beginWork$1 (react-dom.development.js:27219:1)
    at performUnitOfWork (react-dom.development.js:26392:1)
    at workLoopSync (react-dom.development.js:26303:1)
    at renderRootSync (react-dom.development.js:26271:1)
    at recoverFromConcurrentError (react-dom.development.js:25689:1)
    at performConcurrentWorkOnRoot (react-dom.development.js:25589:1)
    at workLoop (scheduler.development.js:266:1)
    at flushWork (scheduler.development.js:239:1)

react-dom.development.js:22670 Uncaught DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at removeChildFromContainer (http://localhost:4000/main.js:11367:15)
    at unmountHostComponents (http://localhost:4000/main.js:24216:9)
    at commitDeletion (http://localhost:4000/main.js:24277:5)
    at commitMutationEffects_begin (http://localhost:4000/main.js:24489:11)
    at commitMutationEffects (http://localhost:4000/main.js:24473:3)
    at commitRootImpl (http://localhost:4000/main.js:26924:5)
    at commitRoot (http://localhost:4000/main.js:26803:5)
    at performSyncWorkOnRoot (http://localhost:4000/main.js:26242:3)
    at flushSyncCallbacks (http://localhost:4000/main.js:12273:22)
    at commitRootImpl (http://localhost:4000/main.js:27062:3)

react-dom.development.js:11996 Uncaught DOMException: Failed to execute 'appendChild' on 'Node': Only one element on document allowed.
    at appendChildToContainer (http://localhost:4000/main.js:11331:16)
    at insertOrAppendPlacementNodeIntoContainer (http://localhost:4000/main.js:24122:7)
    at insertOrAppendPlacementNodeIntoContainer (http://localhost:4000/main.js:24128:7)
    at insertOrAppendPlacementNodeIntoContainer (http://localhost:4000/main.js:24128:7)
    at commitPlacement (http://localhost:4000/main.js:24102:9)
    at commitMutationEffectsOnFiber (http://localhost:4000/main.js:24621:9)
    at commitMutationEffects_complete (http://localhost:4000/main.js:24514:7)
    at commitMutationEffects_begin (http://localhost:4000/main.js:24503:7)
    at commitMutationEffects (http://localhost:4000/main.js:24473:3)
    at commitRootImpl (http://localhost:4000/main.js:26924:5)

react-dom.development.js:11996 Uncaught DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at removeChildFromContainer (http://localhost:4000/main.js:11367:15)
    at unmountHostComponents (http://localhost:4000/main.js:24216:9)
    at commitDeletion (http://localhost:4000/main.js:24277:5)
    at commitMutationEffects_begin (http://localhost:4000/main.js:24489:11)
    at commitMutationEffects (http://localhost:4000/main.js:24473:3)
    at commitRootImpl (http://localhost:4000/main.js:26924:5)
    at commitRoot (http://localhost:4000/main.js:26803:5)
    at performSyncWorkOnRoot (http://localhost:4000/main.js:26242:3)
    at flushSyncCallbacks (http://localhost:4000/main.js:12273:22)
    at commitRootImpl (http://localhost:4000/main.js:27062:3)
```

**How to reproduce the issue:**

1. Install and Enable the Apollo Client Devtools Extension
2. `git clone git@github.com:hrgui/nodejs-react-sc-demo.git` (https://github.com/hrgui/nodejs-react-sc-demo). At the time this was written, commit was at aa4eeaca9c1114c779beb0ee2553d02404aa55a5 (chore: update to react 18)
3. Run `npm install` to install, `npm start` to start
4. Visit http://localhost:4000

**Workarounds**

Workaround 1: Note: in that repo, there is an older commit 53847961a14d1dae0f6305e7ad705e08514ca8fc that uses `react@18.0.0-alpha-a0d991fe6-20211031` and `react-dom@18.0.0-alpha-a0d991fe6-20211031`. This version only shows warnings.

Workaround 2: Disable the Apollo Devtools extension.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome
 - Browser version  99.0.4844.83
 - Extension version 4.0

**Comment by hrgui** [comment]
I am closing this because of the following:

This isn't primarily an Apollo DevTools issue, it is actually more of an application issue. In the above example, I am hydrating the root against the entire document, e.g. `hydrateRoot(document, <App />)`.

Dark Reader also crashes the same application. The application itself requires more thought on what root to hydrate.
